version: 2
jobs:
  build:
    docker:
        - image: eoshep/build-essentials:bionic
    steps:
      - checkout
      - run:
          name: deps
          command: apt-get update && apt-get install -y build-essential libasound2-dev libfreetype6-dev libqt-*
      - run:
          name: compile
          command: export TERM=xterm; make
