version: 2
jobs:
  build:
    docker:
        - image: ubuntu:xenial
    steps:
      - checkout
      - run:
          name: deps
          command: apt-get update && apt-get install -y cmake build-essential libqt5-dev
      - run:
          name: compile
          command: export TERM=xterm; cmake CMakeLists.txt; make
