version: 2
jobs:
  build:
    docker:
        - image: eoshep/build-essentials:bionic
    steps:
      - checkout
      - run:
          name: deps
          command: apt-get update && apt-get install -y cmake build-essential libasound2-dev libqt5waylandcompositor5-dev libfreetype6-dev libqt5-*
      - run:
          name: compile
          command: export TERM=xterm; cmake CMakeLists.txt; make
