version: 2
jobs:
  build:
    docker:
        - image: ubuntu:xenial
    steps:
      - checkout
      - run:
          name: deps
          command: sudo apt-get update && sudo apt-get install -y cmake build-essential libwayland-egl1* libasound2-dev libwayland-* libfreetype6-dev libqt5-*
      - run:
          name: compile
          command: export TERM=xterm; cmake CMakeLists.txt; make
